services:
  backend:
    build:
      context: .
      dockerfile: infrastructure/docker/backend.Dockerfile
  worker:
    build:
      context: .
      dockerfile: infrastructure/docker/worker.Dockerfile
