import type { User } from '../features/auth/types/auth.types';
import type { Listing, UploadJob, AuditLog, RejectedRecord } from '../features/listings/types/listing.types';

// ---------- Vehicle image URLs (Unsplash — free to use) ----------
const vehicleImages = {
  bmw3: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&h=400&fit=crop',
  mercedesC: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&h=400&fit=crop',
  teslaModel3: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=600&h=400&fit=crop',
  audiA4: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&h=400&fit=crop',
  toyotaCamry: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&h=400&fit=crop',
  hondaCivic: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=600&h=400&fit=crop',
  fordMustang: 'https://images.unsplash.com/photo-1584345604476-8ec5f82d661f?w=600&h=400&fit=crop',
  porsche911: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&h=400&fit=crop',
  rangeRover: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=600&h=400&fit=crop',
  volkswagenGolf: 'https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=600&h=400&fit=crop',
  jeepWrangler: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&h=400&fit=crop',
  mazdaCX5: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&h=400&fit=crop',
};

// ---------- Mock Users ----------
export const mockUsers: User[] = [
  {
    id: 'usr_001',
    email: 'john.buyer@example.com',
    displayName: 'John Mitchell',
    role: 'buyer',
    createdAt: '2025-11-15T08:30:00Z',
    lastLoginAt: '2026-08-10T14:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_002',
    email: 'sarah@premiumautos.com',
    displayName: 'Sarah Chen',
    role: 'dealer',
    createdAt: '2025-09-01T10:00:00Z',
    lastLoginAt: '2026-08-10T12:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_003',
    email: 'admin@motorx.com',
    displayName: 'Alex Rivera',
    role: 'admin',
    createdAt: '2025-06-01T09:00:00Z',
    lastLoginAt: '2026-08-10T15:30:00Z',
    isActive: true,
  },
  {
    id: 'usr_004',
    email: 'mike@citycars.com',
    displayName: 'Mike Thompson',
    role: 'dealer',
    createdAt: '2025-10-20T11:00:00Z',
    lastLoginAt: '2026-08-09T18:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_005',
    email: 'emma.b@gmail.com',
    displayName: 'Emma Brooks',
    role: 'buyer',
    createdAt: '2026-01-10T14:00:00Z',
    lastLoginAt: '2026-08-08T09:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_006',
    email: 'raj@elitemotors.com',
    displayName: 'Raj Patel',
    role: 'dealer',
    createdAt: '2026-03-05T16:00:00Z',
    lastLoginAt: '2026-08-07T11:00:00Z',
    isActive: false,
  },
  {
    id: 'usr_007',
    email: 'lisa.w@hotmail.com',
    displayName: 'Lisa Wang',
    role: 'buyer',
    createdAt: '2026-05-22T10:30:00Z',
    lastLoginAt: '2026-08-10T08:00:00Z',
    isActive: true,
  },
  {
    id: 'usr_008',
    email: 'david@autoworld.com',
    displayName: 'David Kim',
    role: 'dealer',
    createdAt: '2026-06-15T09:00:00Z',
    lastLoginAt: '2026-08-10T16:00:00Z',
    isActive: true,
  },
];

// ---------- Mock Listings ----------
export const mockListings: Listing[] = [
  {
    id: 'lst_001',
    dealerId: 'usr_002',
    dealerName: 'Premium Autos',
    make: 'BMW',
    model: '3 Series',
    year: 2023,
    bodyType: 'sedan',
    fuelType: 'petrol',
    transmission: 'automatic',
    condition: 'excellent',
    mileage: 15200,
    color: 'Alpine White',
    vin: 'WBA5R1C50N7B12345',
    price: 42500,
    currency: 'USD',
    title: '2023 BMW 3 Series 330i — Pristine Condition',
    description: 'One-owner vehicle in pristine condition. M Sport package, premium leather, heads-up display, Harman Kardon audio. Full service history at authorized BMW dealer. Winter tires included.',
    images: [
      { id: 'img_001', url: vehicleImages.bmw3, alt: 'BMW 3 Series front', isPrimary: true },
    ],
    status: 'active',
    views: 342,
    leads: 12,
    createdAt: '2026-07-15T10:00:00Z',
    updatedAt: '2026-08-01T14:00:00Z',
  },
  {
    id: 'lst_002',
    dealerId: 'usr_002',
    dealerName: 'Premium Autos',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2022,
    bodyType: 'sedan',
    fuelType: 'diesel',
    transmission: 'automatic',
    condition: 'excellent',
    mileage: 28400,
    color: 'Obsidian Black',
    price: 38900,
    currency: 'USD',
    title: '2022 Mercedes-Benz C300 AMG Line',
    description: 'Stunning C300 with AMG Line exterior, Burmester surround sound, 360° camera, ambient lighting, and panoramic sunroof. Diesel for excellent fuel economy.',
    images: [
      { id: 'img_002', url: vehicleImages.mercedesC, alt: 'Mercedes C-Class', isPrimary: true },
    ],
    status: 'active',
    views: 518,
    leads: 24,
    createdAt: '2026-06-20T09:00:00Z',
    updatedAt: '2026-07-28T11:00:00Z',
  },
  {
    id: 'lst_003',
    dealerId: 'usr_004',
    dealerName: 'City Cars',
    make: 'Tesla',
    model: 'Model 3',
    year: 2024,
    bodyType: 'sedan',
    fuelType: 'electric',
    transmission: 'automatic',
    condition: 'excellent',
    mileage: 8900,
    color: 'Pearl White',
    price: 35000,
    currency: 'USD',
    title: '2024 Tesla Model 3 Long Range — Nearly New',
    description: 'Long Range AWD with Full Self-Driving capability, premium interior, glass roof. Under factory warranty until 2028. Supercharger network included.',
    images: [
      { id: 'img_003', url: vehicleImages.teslaModel3, alt: 'Tesla Model 3', isPrimary: true },
    ],
    status: 'active',
    views: 892,
    leads: 45,
    createdAt: '2026-07-01T08:00:00Z',
    updatedAt: '2026-08-05T16:00:00Z',
  },
  {
    id: 'lst_004',
    dealerId: 'usr_004',
    dealerName: 'City Cars',
    make: 'Audi',
    model: 'A4',
    year: 2021,
    bodyType: 'sedan',
    fuelType: 'petrol',
    transmission: 'automatic',
    condition: 'good',
    mileage: 42100,
    color: 'Navarra Blue',
    price: 29900,
    currency: 'USD',
    title: '2021 Audi A4 45 TFSI Quattro S-Line',
    description: 'S-Line trim with Quattro AWD, virtual cockpit, B&O premium audio, Matrix LED headlights. Well-maintained with full Audi service records.',
    images: [
      { id: 'img_004', url: vehicleImages.audiA4, alt: 'Audi A4', isPrimary: true },
    ],
    status: 'active',
    views: 234,
    leads: 8,
    createdAt: '2026-07-20T14:00:00Z',
    updatedAt: '2026-08-03T10:00:00Z',
  },
  {
    id: 'lst_005',
    dealerId: 'usr_002',
    dealerName: 'Premium Autos',
    make: 'Toyota',
    model: 'Camry',
    year: 2023,
    bodyType: 'sedan',
    fuelType: 'hybrid',
    transmission: 'cvt',
    condition: 'excellent',
    mileage: 19500,
    color: 'Celestial Silver',
    price: 27500,
    currency: 'USD',
    title: '2023 Toyota Camry Hybrid XSE',
    description: 'Top-spec XSE hybrid with sport-tuned suspension, JBL audio, leather seats, Apple CarPlay. Exceptional fuel economy at 44 mpg combined.',
    images: [
      { id: 'img_005', url: vehicleImages.toyotaCamry, alt: 'Toyota Camry', isPrimary: true },
    ],
    status: 'active',
    views: 156,
    leads: 6,
    createdAt: '2026-08-01T11:00:00Z',
    updatedAt: '2026-08-08T15:00:00Z',
  },
  {
    id: 'lst_006',
    dealerId: 'usr_008',
    dealerName: 'Auto World',
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    bodyType: 'hatchback',
    fuelType: 'petrol',
    transmission: 'manual',
    condition: 'good',
    mileage: 35600,
    color: 'Rallye Red',
    price: 22800,
    currency: 'USD',
    title: '2022 Honda Civic Sport Touring Hatchback',
    description: 'Sport Touring hatchback with 6-speed manual, turbocharged 1.5L, Bose audio, moonroof, wireless CarPlay. Fun to drive with great practicality.',
    images: [
      { id: 'img_006', url: vehicleImages.hondaCivic, alt: 'Honda Civic', isPrimary: true },
    ],
    status: 'active',
    views: 287,
    leads: 15,
    createdAt: '2026-07-10T13:00:00Z',
    updatedAt: '2026-08-02T09:00:00Z',
  },
  {
    id: 'lst_007',
    dealerId: 'usr_002',
    dealerName: 'Premium Autos',
    make: 'Ford',
    model: 'Mustang',
    year: 2023,
    bodyType: 'coupe',
    fuelType: 'petrol',
    transmission: 'manual',
    condition: 'excellent',
    mileage: 11200,
    color: 'Grabber Blue',
    price: 39500,
    currency: 'USD',
    title: '2023 Ford Mustang GT Premium — 5.0L V8',
    description: 'The iconic 5.0L V8 Mustang GT with Premium package, MagneRide dampers, active exhaust, Recaro seats. Low miles, garaged since new.',
    images: [
      { id: 'img_007', url: vehicleImages.fordMustang, alt: 'Ford Mustang', isPrimary: true },
    ],
    status: 'active',
    views: 673,
    leads: 31,
    createdAt: '2026-06-28T10:00:00Z',
    updatedAt: '2026-07-30T14:00:00Z',
  },
  {
    id: 'lst_008',
    dealerId: 'usr_004',
    dealerName: 'City Cars',
    make: 'Porsche',
    model: '911 Carrera',
    year: 2021,
    bodyType: 'coupe',
    fuelType: 'petrol',
    transmission: 'automatic',
    condition: 'excellent',
    mileage: 22400,
    color: 'GT Silver',
    price: 98500,
    currency: 'USD',
    title: '2021 Porsche 911 Carrera S — PDK',
    description: 'Stunning 992-generation 911 Carrera S with sport chrono, PASM, sport exhaust, premium package plus. Porsche-maintained with certified pre-owned warranty.',
    images: [
      { id: 'img_008', url: vehicleImages.porsche911, alt: 'Porsche 911', isPrimary: true },
    ],
    status: 'active',
    views: 1245,
    leads: 8,
    createdAt: '2026-07-05T15:00:00Z',
    updatedAt: '2026-08-06T12:00:00Z',
  },
  {
    id: 'lst_009',
    dealerId: 'usr_008',
    dealerName: 'Auto World',
    make: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2023,
    bodyType: 'suv',
    fuelType: 'diesel',
    transmission: 'automatic',
    condition: 'excellent',
    mileage: 16800,
    color: 'Santorini Black',
    price: 72000,
    currency: 'USD',
    title: '2023 Range Rover Sport HSE Dynamic',
    description: 'HSE Dynamic with 22" wheels, air suspension, meridian 3D surround sound, heated/cooled seats, head-up display. Incredible road presence.',
    images: [
      { id: 'img_009', url: vehicleImages.rangeRover, alt: 'Range Rover Sport', isPrimary: true },
    ],
    status: 'active',
    views: 456,
    leads: 19,
    createdAt: '2026-07-18T09:00:00Z',
    updatedAt: '2026-08-04T11:00:00Z',
  },
  {
    id: 'lst_010',
    dealerId: 'usr_004',
    dealerName: 'City Cars',
    make: 'Volkswagen',
    model: 'Golf GTI',
    year: 2022,
    bodyType: 'hatchback',
    fuelType: 'petrol',
    transmission: 'automatic',
    condition: 'good',
    mileage: 31200,
    color: 'Kings Red',
    price: 26500,
    currency: 'USD',
    title: '2022 Volkswagen Golf GTI Autobahn',
    description: 'Autobahn trim with DCC adaptive dampers, Harman Kardon audio, digital cockpit pro, IQ.Drive suite. The quintessential hot hatchback.',
    images: [
      { id: 'img_010', url: vehicleImages.volkswagenGolf, alt: 'VW Golf GTI', isPrimary: true },
    ],
    status: 'sold',
    views: 398,
    leads: 22,
    createdAt: '2026-06-15T12:00:00Z',
    updatedAt: '2026-07-25T10:00:00Z',
  },
  {
    id: 'lst_011',
    dealerId: 'usr_008',
    dealerName: 'Auto World',
    make: 'Jeep',
    model: 'Wrangler',
    year: 2023,
    bodyType: 'suv',
    fuelType: 'petrol',
    transmission: 'automatic',
    condition: 'good',
    mileage: 24600,
    color: 'Sarge Green',
    price: 41200,
    currency: 'USD',
    title: '2023 Jeep Wrangler Rubicon 4xe',
    description: 'Rubicon 4xe plug-in hybrid with removable top, 35" tires, steel bumpers, winch-ready. Trail Rated® and ready for any adventure.',
    images: [
      { id: 'img_011', url: vehicleImages.jeepWrangler, alt: 'Jeep Wrangler', isPrimary: true },
    ],
    status: 'pending',
    views: 189,
    leads: 7,
    createdAt: '2026-08-05T10:00:00Z',
    updatedAt: '2026-08-09T16:00:00Z',
  },
  {
    id: 'lst_012',
    dealerId: 'usr_002',
    dealerName: 'Premium Autos',
    make: 'Mazda',
    model: 'CX-5',
    year: 2024,
    bodyType: 'suv',
    fuelType: 'petrol',
    transmission: 'automatic',
    condition: 'excellent',
    mileage: 5800,
    color: 'Soul Red Crystal',
    price: 31500,
    currency: 'USD',
    title: '2024 Mazda CX-5 Turbo Signature — Like New',
    description: 'Top-of-the-line Signature with turbocharged engine, Nappa leather, Bose 10-speaker, head-up display, ventilated seats. Practically new at just 5,800 miles.',
    images: [
      { id: 'img_012', url: vehicleImages.mazdaCX5, alt: 'Mazda CX-5', isPrimary: true },
    ],
    status: 'active',
    views: 124,
    leads: 4,
    createdAt: '2026-08-08T08:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
  },
];

// ---------- Mock Upload Jobs ----------
export const mockUploadJobs: UploadJob[] = [
  {
    id: 'upl_001',
    dealerId: 'usr_002',
    dealerName: 'Premium Autos',
    fileName: 'premium_autos_inventory_aug2026.csv',
    fileSize: 245760,
    status: 'completed',
    totalRecords: 45,
    processedRecords: 45,
    validRecords: 42,
    rejectedRecords: 3,
    createdAt: '2026-08-01T09:30:00Z',
    completedAt: '2026-08-01T09:32:15Z',
  },
  {
    id: 'upl_002',
    dealerId: 'usr_004',
    dealerName: 'City Cars',
    fileName: 'city_cars_batch_07.csv',
    fileSize: 128000,
    status: 'completedWithErrors',
    totalRecords: 28,
    processedRecords: 28,
    validRecords: 21,
    rejectedRecords: 7,
    createdAt: '2026-07-28T14:00:00Z',
    completedAt: '2026-07-28T14:01:45Z',
  },
  {
    id: 'upl_003',
    dealerId: 'usr_008',
    dealerName: 'Auto World',
    fileName: 'auto_world_full_catalog.csv',
    fileSize: 512000,
    status: 'processing',
    totalRecords: 120,
    processedRecords: 67,
    validRecords: 65,
    rejectedRecords: 2,
    createdAt: '2026-08-10T15:00:00Z',
  },
  {
    id: 'upl_004',
    dealerId: 'usr_002',
    dealerName: 'Premium Autos',
    fileName: 'quick_add_3_vehicles.csv',
    fileSize: 8192,
    status: 'failed',
    totalRecords: 3,
    processedRecords: 0,
    validRecords: 0,
    rejectedRecords: 0,
    createdAt: '2026-08-09T11:00:00Z',
    completedAt: '2026-08-09T11:00:05Z',
  },
  {
    id: 'upl_005',
    dealerId: 'usr_004',
    dealerName: 'City Cars',
    fileName: 'city_cars_new_arrivals.csv',
    fileSize: 65536,
    status: 'pending',
    totalRecords: 15,
    processedRecords: 0,
    validRecords: 0,
    rejectedRecords: 0,
    createdAt: '2026-08-10T15:55:00Z',
  },
];

// ---------- Mock Rejected Records ----------
export const mockRejectedRecords: RejectedRecord[] = [
  { row: 5, data: { make: 'BMW', model: '', year: '2023', price: '45000' }, errors: ['Model is required'] },
  { row: 12, data: { make: 'Toyota', model: 'Corolla', year: 'abc', price: '22000' }, errors: ['Year must be a valid number'] },
  { row: 18, data: { make: 'Honda', model: 'Accord', year: '2022', price: '-5000' }, errors: ['Price must be a positive number'] },
  { row: 23, data: { make: '', model: 'Civic', year: '2021', price: '19000' }, errors: ['Make is required'] },
  { row: 31, data: { make: 'Ford', model: 'F-150', year: '2025', price: '55000' }, errors: ['Year cannot be in the future'] },
  { row: 37, data: { make: 'Audi', model: 'Q5', year: '2020', price: '' }, errors: ['Price is required'] },
  { row: 42, data: { make: 'Mercedes-Benz', model: 'E-Class', year: '1899', price: '35000' }, errors: ['Year must be 1900 or later'] },
];

// ---------- Mock Audit Logs ----------
export const mockAuditLogs: AuditLog[] = [
  {
    id: 'aud_001',
    eventType: 'dealer_approved',
    actorId: 'usr_003',
    actorName: 'Alex Rivera',
    targetId: 'usr_008',
    targetName: 'Auto World',
    details: 'Dealer application approved after document verification',
    timestamp: '2026-08-10T14:30:00Z',
  },
  {
    id: 'aud_002',
    eventType: 'user_suspended',
    actorId: 'usr_003',
    actorName: 'Alex Rivera',
    targetId: 'usr_006',
    targetName: 'Raj Patel',
    details: 'Account suspended due to policy violation',
    timestamp: '2026-08-09T16:00:00Z',
  },
  {
    id: 'aud_003',
    eventType: 'upload_completed',
    actorId: 'usr_002',
    actorName: 'Premium Autos',
    targetId: 'upl_001',
    targetName: 'premium_autos_inventory_aug2026.csv',
    details: '45 records processed, 42 valid, 3 rejected',
    timestamp: '2026-08-01T09:32:15Z',
  },
  {
    id: 'aud_004',
    eventType: 'listing_removed',
    actorId: 'usr_003',
    actorName: 'Alex Rivera',
    targetId: 'lst_099',
    targetName: '2019 Honda Accord — Flagged listing',
    details: 'Listing removed for misleading vehicle condition description',
    timestamp: '2026-07-30T11:00:00Z',
  },
  {
    id: 'aud_005',
    eventType: 'dealer_rejected',
    actorId: 'usr_003',
    actorName: 'Alex Rivera',
    targetId: 'usr_099',
    targetName: 'Quick Sales LLC',
    details: 'Application rejected — invalid business license',
    timestamp: '2026-07-28T09:30:00Z',
  },
  {
    id: 'aud_006',
    eventType: 'user_activated',
    actorId: 'usr_003',
    actorName: 'Alex Rivera',
    targetId: 'usr_006',
    targetName: 'Raj Patel',
    details: 'Account reactivated after appeal review',
    timestamp: '2026-08-10T10:00:00Z',
  },
];

// ---------- Helpers ----------
export function formatPrice(price: number, currency = 'USD'): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(price);
}

export function formatMileage(mileage: number): string {
  return new Intl.NumberFormat('en-US').format(mileage) + ' mi';
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric',
    hour: 'numeric', minute: '2-digit',
  });
}

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
}

export function getInitials(name: string): string {
  return name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2);
}

// Available makes for filter dropdowns
export const availableMakes = [
  'Audi', 'BMW', 'Ford', 'Honda', 'Jeep', 'Land Rover', 'Mazda',
  'Mercedes-Benz', 'Porsche', 'Tesla', 'Toyota', 'Volkswagen',
];

export const bodyTypes = ['sedan', 'suv', 'hatchback', 'coupe', 'truck', 'van', 'wagon', 'convertible'] as const;
export const fuelTypes = ['petrol', 'diesel', 'electric', 'hybrid', 'plug-in-hybrid'] as const;
export const transmissionTypes = ['automatic', 'manual', 'cvt'] as const;
