"""MotorX test-case definitions used by build_test_plan.py (one tuple per case group)."""

unit = [
    ('apps/backend/src/test/db.safety.test.ts', 'Test database target safety', 'Test infrastructure; RR-09', 'Local, Docker, non-test, remote and wrong-scheme URIs; missing TEST_MONGODB_URI.', 'Validate each URI before any connection.', 'Only a motorx_test database on an approved host is accepted; never falls back to MONGODB_URI.'),
    ('apps/backend/src/config/mongoUri.test.ts', 'Production database URI guard', 'PSR-10; RR-09', 'Atlas SRV, TLS/non-TLS, local and test database names.', 'Check each URI with findProductionMongoUriProblems.', 'Production refuses unencrypted, local, test/dev databases and URIs without a database name.'),
    ('apps/backend/src/modules/admin/admin.validation.test.ts', 'Admin request validation', 'FR-ADMIN-02–05', 'Default and bounded pages; user/listing filters; invalid status.', 'Parse query schemas.', 'Defaults and valid filters parse; unsupported values fail.'),
    ('apps/backend/src/modules/dealers/dealer.validation.test.ts', 'Dealer application validation', 'FR-DEALER-02,09–13', 'Multipart fields; incomplete application; missing rejection reason.', 'Parse application and review schemas.', 'Form values normalized; incomplete data and missing rejection reason rejected.'),
    ('apps/backend/src/modules/dealers/dealerDocument.content.test.ts', 'Dealer document content checks', 'FR-DEALER-09; PSR-13–14', 'Plain PDF; PDFs with JavaScript, launch action, embedded file; renamed executable; images with metadata; fake JPEG.', 'Detect type from bytes and sanitize each file.', 'Only safe PDFs and re-encoded images are kept; dangerous or disguised files are rejected.'),
    ('apps/backend/src/modules/inventory/inventory.validation.test.ts', 'CSV upload validation', 'FR-UPLOAD-01–03,07', 'Car and motorcycle headers; missing headers; binary files; paging.', 'Validate files, headers and pagination.', 'Matching headers accepted per category; bad content and missing fields rejected; paging bounded.'),
    ('apps/backend/src/modules/inventory/inventory.service.test.ts', 'Upload acceptance and controlled retry', 'FR-UPLOAD-04–06; RR-06–08', 'Queue available, down, and hanging; dealer at listing limit; job-creation failure; failed and non-failed uploads.', 'Accept uploads and request retries with mocked queue and storage.', 'Uploads are kept for later queuing when Redis is down, the dealer is never kept waiting, storage is cleaned on failure, and only the owner’s failed jobs can be retried.'),
    ('apps/backend/src/modules/marketplace/listing.validation.test.ts', 'Listing validation and identity', 'FR-MARKET-02–05; FR-ETL-19–21', 'Plate variants, pagination, inverted ranges, empty edits, image order, category/powertrain fixtures.', 'Normalize registrations and parse listing schemas.', 'Equivalent plates share one identity; invalid edits, ranges and attributes fail.'),
    ('apps/backend/src/modules/marketplace/listingImage.service.test.ts', 'Image signature check', 'FR-MARKET-13; PSR-14', 'JPEG, PNG, WebP headers; spoofed JPEG; GIF.', 'Check each file signature.', 'Supported signatures accepted; spoofed and unsupported files rejected.'),
    ('apps/backend/src/shared/utils/imageReencode.test.ts', 'Image re-encoding', 'FR-MARKET-13; PSR-13–14', 'JPEG with GPS EXIF and rotation; trailing hidden data; 41-megapixel bomb; fake image; SVG/GIF; PNG document.', 'Re-encode each image.', 'Output is a clean WebP (or PNG for documents), upright, without metadata or hidden data; bombs and disallowed formats refused.'),
    ('apps/backend/src/scripts/listingImageMigration.test.ts', 'Photo migration and small copies', 'PSR-13; Extension (small photo copies)', 'Old root-level photos with GPS; already migrated photos; dry run; CDN URL; photo without small copy; missing and undecodable objects.', 'Run the migration against an in-memory bucket.', 'Photos moved as clean WebP; re-runs skip finished work; dry run changes nothing; an 800 px small copy is created once and its URL recorded; problems reported, not hidden.'),
    ('apps/backend/src/modules/search/search.queryAnalyzer.test.ts', 'Search query analysis', 'FR-SEARCH-08–20; FR-ETL-28', '“automatic SUV under 2 million near Colombo”; “toyata corola”; mileage vs price; oversized query; vector fixture.', 'Analyze queries and normalize embeddings.', 'Correct structured filters and typo corrections; bounded input; normalized 384-length vectors.'),
    ('apps/backend/src/modules/buyers/buyer.similarity.test.ts', 'Vehicle similarity scoring', 'Extension (similar vehicles, recommendations)', 'Same model, same make, other make; price and year differences; case/spacing; view order.', 'Score candidates against one or several viewed vehicles.', 'Closer vehicles score higher; recent views weigh more; ties keep newest-first order.'),
    ('apps/backend/src/shared/utils/pagination.test.ts', 'Pagination metadata', 'FR-SEARCH-06', 'Partial final page; empty collection.', 'Build pagination metadata.', 'Correct page counts; zero pages when empty.'),
    ('apps/backend/src/shared/middleware/verifyFirebaseToken.test.ts', 'Token verification cache', 'FR-USER-07–09; PSR-08', 'Valid, revoked, expiring and missing tokens.', 'Call the middleware repeatedly with a mocked Firebase Admin SDK.', 'Firebase (with revocation) checked once per cache period; never trusted past token expiry; failures not cached.'),
    ('apps/worker/src/pipeline/extract.test.ts', 'CSV extraction', 'FR-ETL-05–06', 'Multi-batch CSV stream; wrong column count.', 'Stream records and record progress.', 'Bounded batches with cumulative progress; malformed rows fail.'),
    ('apps/worker/src/pipeline/normalize.test.ts', 'Vehicle normalization', 'FR-ETL-07,23', 'Whitespace, enum aliases, price suffixes, blank optional cells, motorcycle rows, titles cut short to a prefix of make and model.', 'Normalize rows per category.', 'Consistent values; blanks stay unset; category-specific attributes; a truncated title such as “Toyota Pre” becomes “Toyota Premio”, while a longer title is kept.'),
    ('apps/worker/src/pipeline/transform.test.ts', 'Batch transformation', 'FR-ETL-08–17; RR-05', 'Mixed valid/invalid rows; electric car row.', 'Prepare a batch with known starting row numbers.', 'Valid rows kept; invalid rows isolated with their CSV row numbers.'),
    ('apps/worker/src/pipeline/validate.test.ts', 'Category and powertrain rules', 'FR-MARKET-03; FR-ETL-08–11', 'Petrol, diesel, hybrid, electric, plug-in hybrid cars and five other categories.', 'Validate valid and invalid combinations.', 'Engine or battery data required as appropriate; field-level errors returned.'),
    ('apps/worker/src/services/uploadJob.service.test.ts', 'CSV ETL orchestration', 'FR-ETL-13–22,31–33; RR-06–08', 'Mocked storage/repositories: mixed rows, malformed CSV, duplicates, temporary storage failure, exhausted attempts, crash mid-import, listing limit, lost lease.', 'Run the import service and inspect writes and counters.', 'Accurate counters; permanent vs temporary failures handled differently; resumes from the last checkpoint with no row imported twice; stops when the lease is lost.'),
    ('apps/worker/src/services/imageProcessing.service.test.ts', 'ZIP photo processing', 'FR-MARKET-12–16; RR-06; Extension (small copies)', 'ZIPs with slash/backslash paths, an extra wrapper folder, photos whose extension does not match their content, unknown folders, root files, oversize entries, fake and huge images, storage errors, retries, and a ZIP with no photo in any folder.', 'Process ZIPs with mocked storage and repositories.', 'Photos matched by the folder that contains them (normalized plate), cleaned and resized, an 800 px copy stored and linked; a ZIP with no photos in folders fails at once with instructions; unsafe archives fail at once; retries never attach a photo twice.'),
    ('apps/worker/src/services/jobLease.test.ts', 'Job lease renewal', 'RR-06–08', 'Long-running job; takeover by another worker; renewal error; job end.', 'Hold a lease with fake timers.', 'Lease renewed every third of its duration; loss detected; temporary errors tolerated; renewal stops at the end.'),
    ('apps/worker/src/services/transientError.test.ts', 'Retry classification', 'RR-06–08', 'Network, throttling, 5xx, MongoDB unreachable; missing file, access denied, parse and duplicate errors.', 'Classify each error.', 'Only temporary failures are retried.'),
    ('apps/worker/src/jobs/reaper.job.test.ts', 'Lost-job reconciliation', 'FR-ETL-03; RR-06–08', 'Pending uploads with missing, waiting, delayed or active queue messages; exhausted budgets.', 'Run one reaper cycle with mocked queue.', 'Lost jobs re-queued under the right job ID; jobs with a live message untouched; exhausted jobs failed instead of looping.'),
    ('apps/worker/src/jobs/emailOutbox.job.test.ts', 'Email outbox delivery', 'FR-NOTIFY-06–07; RR-08', 'Due emails; SMTP failures on attempts 1–5; deleted recipient.', 'Run outbox cycles with a mocked mailer.', 'Each email sent once; retries after 1 min, 5 min … 2 h; failed after the fifth attempt; bounded work per cycle.'),
    ('apps/worker/src/jobs/documentRetention.job.test.ts', 'Document retention', 'FR-DEALER-13; PSR-15', 'Decisions older than 90 days; storage delete failure.', 'Run one retention cycle.', 'Files deleted then record cleared; a failed delete is retried next cycle.'),
    ('apps/worker/src/jobs/staleListingReminder.job.test.ts', 'Stale-stock reminders', 'Extension (stale stock)', 'Dealers with stale listings; claim won or lost; one dealer failing.', 'Run one reminder cycle with mocked repositories.', '60-day cutoff and 7-day repeat applied; each dealer gets their own count once; one failure does not stop the others.'),
    ('apps/frontend/src/features/auth/components/RoleGuard.test.tsx', 'Role-protected pages', 'FR-USER-10–12', 'Signed-out, allowed, disallowed and pending-applicant users.', 'Render protected routes.', 'Redirect to login, show page, show “Access Restricted” or send to the application status page as appropriate.'),
    ('apps/frontend/src/features/auth/components/EmailVerificationBanner.test.tsx', 'Email verification banner', 'FR-USER-04', 'Verified, unverified and signed-out users.', 'Render the banner and resend/refresh.', 'Shown only when needed; resend works; hides once verified.'),
    ('apps/frontend/src/features/auth/context/AuthProvider.test.tsx', 'Per-account data isolation', 'FR-USER-12; PSR-09', 'Sign-out; a different account signing in on the same browser.', 'Switch accounts and inspect the query cache.', 'Previous account’s cached data is cleared before the next user can see it.'),
    ('apps/frontend/src/features/auth/pages/RegisterPage.test.tsx', 'Dealer application from an existing account', 'FR-DEALER-09–13', 'Rejected and pending applications for a signed-in buyer.', 'Render the application page and resubmit.', 'Rejection reason shown, answers pre-filled, no password asked, resubmission sent with new documents; pending applicants redirected.'),
    ('apps/frontend/src/portals/dealer/pages/DealerProfile.test.tsx', 'Dealer profile editing', 'FR-DEALER-01–04', 'Approved dealer profile; server error.', 'Edit and save.', 'Verified name and registration read-only; edits saved and confirmed; server errors shown.'),
    ('apps/frontend/src/portals/dealer/pages/UploadDetails.test.tsx', 'Upload details and publish-all', 'FR-UPLOAD-06–08; Extension (bulk)', 'Failed CSV, failed photos, refused retry, successful upload with 9 drafts.', 'Render the page and use Retry and Publish all.', 'Failure reasons and retries work; all drafts of the upload are published in one request after confirmation.'),
    ('apps/frontend/src/portals/dealer/pages/ListingManager.test.tsx', 'Bulk and stale-stock tools', 'FR-DEALER-05–08; Extension (bulk, stale)', 'Stats with 2 stale listings; draft and stale listings.', 'Use the banner, select-all bulk publish, one-click “Still available” and the price dialog.', 'Stale banner opens the stale list; one request publishes all selected; age shown; price cut previewed (5,400,000 at 10%) then applied; skipped listings explained.'),
    ('apps/frontend/src/portals/admin/pages/adminPages.test.tsx', 'Admin approvals, dashboard and monitoring', 'FR-ADMIN-03–08', 'Deep links with status/applicationId/uploadId; failing sections; date ranges.', 'Render admin pages from links.', 'Correct tab and exact application highlighted; failures shown as unavailable, not zero; filters passed to the server.'),
    ('apps/frontend/src/portals/buyer/pages/VehicleDetails.test.tsx', 'Vehicle page on phones', 'FR-MARKET-07–11; Extension (mobile, discovery)', 'Listing with three photos (small copies) and a dealer phone 077 123 4567.', 'Render, swipe, tap arrows, scroll vertically.', 'Call/WhatsApp/Email bar with the WhatsApp message ready (94771234567); small copy chosen via srcset; swipe changes photo, vertical scroll does not; vehicle remembered for recommendations; similar vehicles shown.'),
    ('apps/frontend/src/features/compare/compare.test.tsx', 'Compare vehicles', 'Extension (compare)', 'Four vehicles; two vehicles with different price/year/mileage; one unavailable.', 'Add to compare, open comparison.', 'At most three; full list explained; best price, year and mileage highlighted; unavailable vehicle stated.'),
    ('apps/frontend/src/shared/components/mobileLayout.test.tsx', 'Mobile navigation and card tables', 'UR-01–04; Extension (mobile)', 'Portal with two pages; table with two columns.', 'Open menu, press Escape, choose a page; render a table.', 'Drawer opens with focus inside; closes on Escape (focus returns) and after navigation; every cell labelled with its column.'),
    ('apps/frontend/src/shared/i18n/i18n.test.tsx', 'Sinhala and Tamil', 'Extension (languages)', 'All dictionaries; Tamil browser preference.', 'Compare dictionaries; switch language; reload.', 'Every message translated with identical placeholders; whole site switches, page lang set, choice remembered; Tamil chosen automatically for a Tamil browser.'),
    ('apps/frontend/src/shared/utils/phone.test.ts', 'WhatsApp number formatting', 'Extension (mobile contact)', 'Local, +94, 9-digit, foreign and invalid numbers.', 'Convert numbers and build links.', 'Sri Lankan numbers get 94; foreign numbers kept; undialable numbers give no link.'),
    ('apps/backend/src/modules/inventory/inventory.queue.test.ts', 'Queue publishing for repeat photo uploads', 'FR-UPLOAD-08; RR-06–08', 'Existing queue jobs that are completed, failed, waiting, active or delayed.', 'Publish CSV and photo jobs with a mocked queue.', 'A finished job is removed and queued again under the same ID, so photos attached a second time are processed; a job still waiting or running is never duplicated (finding F-09).')]

integration_auto_list = [
    ('apps/backend/src/modules/dealers/dealer.repository.test.ts', 'Dealer application persistence', 'FR-DEALER-09', 'Empty test database; valid application.', '1. Create an application. 2. Find it by user ID.', 'One pending application with the stored fields.'),
    ('apps/backend/src/modules/admin/admin.repository.test.ts', 'Pending applications oldest first', 'FR-ADMIN-03', 'Two applications submitted in order.', '1. Create A then B. 2. List pending.', 'Both returned, oldest submission first.'),
    ('apps/backend/src/modules/marketplace/listing.repository.test.ts', 'Registration uniqueness in MongoDB', 'FR-ETL-19–22; RR-08', 'Active, archived and differently formatted plates.', '1. Look up duplicates. 2. Insert a second draft/active listing with the same plate. 3. Relist after archiving.', 'Duplicates found across formats; the database itself rejects a second open listing; archived plates can be relisted.'),
    ('apps/backend/src/modules/marketplace/listing.service.test.ts', 'Listing update persistence', 'FR-MARKET-05', 'Owned listing with a description.', '1. Set description to null. 2. Set a new description.', 'Description removed, then updated, in the stored document.'),
    ('apps/backend/src/modules/admin/admin.documentAccess.test.ts', 'Audited document access', 'FR-ADMIN-06; PSR-15', 'Dealer with documents; deleted documents; invalid index.', '1. Admin opens a document. 2. Open after retention deletion. 3. Open a missing index.', 'Each view audited with who and which file; 410 Gone after deletion without an audit entry; no entry for a missing file.'),
    ('apps/backend/src/shared/middleware/rateLimits.test.ts', 'Rate limits with real Redis', 'PSR-13; RR-10', 'Limiter with small budget; Redis unavailable; real Redis store.', '1. Exceed the budget. 2. Stop the store. 3. Count only successes. 4. Share one budget via Redis. 5. Exceed upload concurrency.', '429 in the standard format; requests allowed when Redis is down; one shared budget across instances; 503 with Retry-After beyond the upload limit.'),
    ('apps/backend/src/scripts/listingImageMigration.db.test.ts', 'Photo URL updates in MongoDB', 'PSR-13; Extension (small photo copies)', 'Listing whose photo keys contain dots, as real keys do.', '1. Set the small-copy URL on one photo. 2. Rewrite both photo URLs.', 'Only the listed photos change and all other image fields are kept (regression test for finding F-08).'),
    ('apps/worker/src/repositories/jobSafety.db.test.ts', 'Lease ownership and idempotent writes', 'RR-06–08; FR-ETL-31–32', 'Upload job with an expired and a valid lease; repeated batches.', '1. Take over an expired lease and write as the old owner. 2. Try to claim a job with a valid lease. 3. Insert the same CSV row twice. 4. Record the same rejection twice.', 'Only the current owner can write; a valid lease cannot be stolen; one listing per CSV row and one rejection per bad row.')]

integration_journeys = [
    ('apps/backend/src/test/accessControl.journey.test.ts', 'Access control across dealers and roles', 'FR-USER-07–12; PSR-08–09; FR-DEALER-10', 'Buyer, dealers A and B, admin and a suspended user; listings, uploads, documents and notifications owned by A.', '1. As B, request, edit, delete and retry A’s resources by ID. 2. Read drafts and private storage publicly. 3. Call dealer/admin routes without a token and with wrong roles. 4. Use a suspended account’s valid token. 5. Approve an applicant with an unverified email.', 'Every foreign access is refused with no change to A’s data; drafts and private objects never public; 401/403 as appropriate; suspended accounts blocked; approval refused until the email is verified.'),
    ('apps/backend/src/test/dealerLifecycle.journey.test.ts', 'Dealer lifecycle and admin monitoring', 'FR-DEALER-01–13; FR-ADMIN-03–07', 'Buyer applying from an existing account; admin; listings of a dealer who is later suspended.', '1. Suspend a dealer and check browse, details and search; reactivate. 2. Edit the dealer profile. 3. Apply as a signed-in buyer; reject; correct and resubmit. 4. Try to apply again once approved. 5. Filter uploads and audit logs by ID and date.', 'Suspended dealers’ listings vanish from all public views and return on reactivation; only allowed profile fields change; resubmission keeps history and replaces documents; filters return exactly the matching records.'),
    ('apps/backend/src/test/listingTools.journey.test.ts', 'Bulk tools, stale stock and discovery', 'FR-DEALER-05–08; Extension (bulk, stale, discovery, small copies)', 'Two dealers; drafts, active, sold and archived listings; listings of one CSV upload; stale dates; a suspended dealer; photos with small copies.', '1. Bulk publish chosen drafts and all drafts of one upload. 2. Send a rival’s IDs. 3. Mark sold, archive, cut prices 10%, delete archived. 4. Send invalid bulk requests and a buyer’s request. 5. Check stale counts, ordering and fresh-again actions. 6. Request similar and recommended vehicles. 7. Fetch a small photo copy.', 'Only eligible own listings change and the rest are counted as skipped; prices 6,000,000 → 5,400,000; photos and small copies deleted from storage; invalid requests 400, buyers 403; stale = active and unconfirmed for 60 days (legacy listings by update time); similar and recommended lists are ranked, exclude the seed/viewed and hidden listings; small copy served from thumbs/.')]

planned_it = [
    ('IT-12', 'Real Firebase identity', 'FR-USER-01–09; PSR-08', 'Dedicated test Firebase project or emulator [7]; buyer and dealer test accounts.', '1. Sign in and call /api/v1/auth/me twice. 2. Revoke the refresh token; call again after the cache period. 3. Delete the Firebase user.', 'One local profile per Firebase user; revoked or deleted users lose access within the cache period (2 minutes).'),
    ('IT-13', 'Real SMTP delivery and failure', 'FR-NOTIFY-06–07', 'Test mailbox or local mail sink; failed import and approval events.', '1. Trigger the events. 2. Check received mail. 3. Break SMTP credentials and trigger again.', 'Mail arrives with the right content; with SMTP broken, in-app notifications remain and email status becomes pending then failed after five attempts.'),
    ('IT-14', 'CSV and ZIP through queue and live worker', 'FR-UPLOAD-04–08; FR-ETL-01–33', 'Running backend + worker + Redis + MinIO; CSV with valid, invalid and duplicate rows; ZIP with matching and unknown folders.', '1. Upload the CSV through the API. 2. Wait for completion. 3. Upload the ZIP. 4. Inspect listings, rejected rows, photos and small copies.', 'Counts match the fixture; rejected rows keep their row numbers; photos and small copies attached only to this upload’s listings; unknown folder reported.'),
    ('IT-15', 'Search relevance on a labelled dataset', 'FR-SEARCH-01–20', 'Over 300 listings including older exact matches; 20 pre-labelled queries.', '1. Run each query with semantic search on and off. 2. Record the top five.', 'Hard filters always hold; the labelled match is in the top five for at least 18 of 20 queries (proposed target).')]

e2e = [
    ('E2E-01', 'Buyer registration, sign-in and session', 'FR-USER-01–06A', 'Unused test email; existing buyer account.', '1. Open /signup; submit with missing fields and mismatched passwords. 2. Register a valid buyer; open the verification email. 3. Sign out and sign in. 4. Try a wrong password and a duplicate email. 5. Reload /marketplace while signed in.', 'Clear field errors; one account created; verification banner disappears after verifying; wrong password shows “The email address or password is incorrect.”; session survives reload.'),
    ('E2E-02', 'Dealer application and approval', 'FR-DEALER-09–13; FR-ADMIN-03,06', 'Applicant with a PDF registration and ID; admin in a second browser profile.', '1. Apply at /dealer/apply. 2. Check the status page and that /dealer is refused. 3. Admin opens Dealer Approvals from the dashboard link, views both documents and approves. 4. Applicant signs in again.', 'Application appears in Pending (oldest first); document views appear in Audit Logs; applicant reaches the Dealer Dashboard; an approval notification appears.'),
    ('E2E-03', 'Rejection, correction and resubmission', 'FR-DEALER-11–13', 'Pending applicant; admin.', '1. Admin rejects with a reason. 2. Applicant opens the status page and chooses “Correct and resubmit”. 3. Changes a field, attaches new documents and resubmits. 4. Admin reviews again.', 'Reason shown to the applicant; form pre-filled without a password field; resubmission returns to Pending with the earlier rejection shown in its history.'),
    ('E2E-04', 'Create, edit, publish and photograph a vehicle', 'FR-MARKET-01–05,07–16', 'Approved dealer; unique car; two photos; buyer profile.', '1. Add New Vehicle with two photos as a draft. 2. Edit the price. 3. Publish from My Listings. 4. As buyer, open it from the marketplace. 5. Dealer removes one photo; buyer reloads.', 'Draft not visible to the buyer; after publishing, details, price and dealer contacts are correct; removed photo no longer shown; photos load the small copy on a phone-width window (check the Network tab).'),
    ('E2E-05', 'Recover from a failed photo upload', 'FR-MARKET-12–15; RR-08–09', 'New vehicle; block the image request once (DevTools request blocking).', '1. Create the vehicle with two photos while one request is blocked. 2. Read the error. 3. Unblock and use “Retry images”. 4. Press Create again once, deliberately.', 'Exactly one listing exists; the missing photo can be added from the edit page; pressing Create again is refused as a duplicate registration, not a second listing.'),
    ('E2E-06', 'CSV import, corrections and ZIP photos', 'FR-UPLOAD-01–08; FR-ETL-13–22,31–33', 'Category template; CSV with valid, invalid and duplicate rows; ZIP with a matching and an unknown folder.', '1. Download the car template. 2. Upload the mixed CSV and watch the status. 3. Read rejected rows. 4. Upload the ZIP. 5. Use “Publish all N” on the upload page. 6. Check the marketplace.', 'Counters match the file; each rejection names the row and reason; unknown folder listed; after Publish all, every valid vehicle is public with its photos; notifications match the result.'),
    ('E2E-07', 'Buyer search, filters and dealer contact on a phone', 'FR-MARKET-07–11,16; FR-SEARCH-01–20; Extension (mobile)', 'Seeded catalogue; DevTools device mode at 390 × 844.', '1. Search “automatic SUV under 8 million near Colombo”. 2. Open “Filters (n)”, add a make, press “Show N vehicles”. 3. Try “toyata corola” and a no-match query. 4. Open a vehicle; swipe the photos; tap WhatsApp.', 'Results respect the filters; the sheet shows the active filter count; empty results explain what to do; swipe changes photos; WhatsApp opens with the number in 94… form and the message pre-filled.'),
    ('E2E-08', 'Similar vehicles, recommendations and compare', 'Extension (discovery, compare)', 'Catalogue with several makes; fresh browser profile.', '1. Open three vehicles. 2. Return to the marketplace and check “Recommended for you”. 3. On a vehicle page, check “Similar vehicles”. 4. Add three vehicles to compare; try a fourth. 5. Open “Compare now”, remove one, reload, copy the link to another profile.', 'Recommendations appear only after viewing and never include the viewed vehicles; similar vehicles exclude the current one; fourth vehicle refused with a message; best price/year/mileage highlighted; the shared link shows the same comparison.'),
    ('E2E-09', 'Bulk actions and stale stock', 'FR-DEALER-05–08; Extension (bulk, stale)', 'Dealer with drafts and at least one active listing whose lastConfirmedAt is older than 60 days (set in the test database).', '1. Open the dashboard and read the stale banner. 2. Review now → Needs attention. 3. Use Still available, Reduce price 10% and Mark sold on different rows. 4. On My Listings, select all drafts and Publish. 5. Archive two and Delete permanently.', 'Counts in the banner and tab match; each action updates the list and the counts; reduced price shown to buyers; skipped listings explained; deleted listings and photos gone.'),
    ('E2E-10', 'Stale-stock reminder notification', 'Extension (stale stock); FR-NOTIFY-01–03', 'Worker running the baseline; dealer with stale listings.', '1. Start the worker. 2. Open the dealer’s notification bell. 3. Click the reminder. 4. Restart the worker.', 'One reminder with the correct count; clicking opens the Needs attention list; no second reminder within 7 days after restart.'),
    ('E2E-11', 'Administrator moderation and suspension', 'FR-ADMIN-01–06,09–10; FR-USER-10–11', 'Admin and an active dealer with public listings.', '1. Suspend the dealer. 2. As buyer, search for their vehicle. 3. As the dealer, try to edit a listing. 4. Reactivate. 5. Check Audit Logs filtered by today.', 'Suspended dealer’s vehicles disappear from browse, search and details; dealer actions refused; everything returns after reactivation; both actions audited with the admin’s name.'),
    ('E2E-12', 'Responsive layout and keyboard use', 'UR-01–04,09–12,16–18; Extension (mobile)', 'Widths 360, 390, 768 and 1440 px; keyboard only.', '1. On each width, use the menu in the buyer site and in the dealer and admin portals. 2. Open and close the filter sheet, compare tray and price dialog with Tab/Enter/Escape. 3. View My Listings and Upload Monitoring on a phone width. 4. Tap an input on an iPhone-size width.', 'No page scrolls sideways; menus reachable at every width and close on Escape; focus visible and returned; tables show as labelled cards; inputs do not zoom the page; buttons at least 44 px tall.'),
    ('E2E-13', 'Sinhala and Tamil', 'Extension (languages)', 'Native Sinhala and Tamil readers if available.', '1. Choose සිංහල in the navbar, browse, search and open a vehicle. 2. Reload. 3. Choose தமிழ் and repeat. 4. Sign in page in each language.', 'All buyer pages and sign-in change language; choice survives reload; text fits on a phone; readers confirm wording is natural (record their comments).'),
    ('E2E-14', 'Notification centre and email status', 'FR-NOTIFY-01–07', 'Dealer and admin; test mailbox.', '1. Trigger a failed import and an approval. 2. Check bell counts. 3. Open and mark read; reload. 4. Check another user’s inbox.', 'Right recipient, correct unread count after reload, email status shown; other users see nothing of it.'),
    ('E2E-15', 'Mobile performance audit', 'PSR-01; Extension (mobile)', 'Production build served locally; Lighthouse in Chrome, mobile preset.', '1. Audit the landing page, marketplace and one vehicle page. 2. Save the reports.', 'Record Performance, Accessibility and Best Practices scores and LCP; compare with the pre-mobile baseline if available.')]
